CREATE TABLE dados (
    AlunoID INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR(50) NOT NULL,
    Sobrenome VARCHAR(50) NOT NULL,
    Endereco VARCHAR(150) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Host VARCHAR(50) NOT NULL
);